#!/bin/bash

# if file .de_bug exists then  append the date and $@ command

if [ -e $HOME/.de_bug ] ; then
  date | tee -a $HOME/.de_bug
  echo cmd:$@ | tee -a $HOME/.de_bug
  $@ | tee -a $HOME/.de_bug
fi 

# sample
# touch ~/.de_bug
#   #!/usr/bin/env bash
#   de_bugit ls -al
#   de_bugit df -h
#   de_bugit ps -aux
#  vim ~/.de_bug
