#!/bin/bash

filechek() {
if [ -e $1 ] ; then
#   echo $1 exists 
    if [ -f $1 ]; then
       echo $1 reaglar file
    else
#      echo $1 non regular
       if [ -d $1 ]; then
         echo $1 is a directory
       else
         echo $1 exists nonfile/nondirectory
       fi
    fi
else
    echo $1 does not exist
fi
echo "inside filechek function " $1
}
filechek /home/rchansen/.local/bin
filechek /home/rchansen/bin
filechek /home/rchansen/bin/f
filechek /home/rchansen/bingit/$1
filechek /home/bin/www

x='/home/bin/ww'
if [ -L $x ]; then
  echo $x "link"
fi
