#!/usr/bin/env bash
#
# Invoke pylint but not have to type switch info
# semi taken from ESR src install using pylint
# get the pylint doc in a pdf to help read the message
# https://media.readthedocs.org/pdf/pylint/latest/pylint.pdf


# from Eric S. Raymond
COMMON_PYLINT='--rcfile=/dev/null --reports=n 
	--msg-template="{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}" '
#	--dummy-variables-rgx='^_'
PYLINTOPTS="C0103,C0123,C0301,C0302,C0325,C0326,C0330,C0410,C1001,C0111,R0101,R0902,R0903,R0904,R0201,R0912,R0913,R0914,R0915,R1705,W0110,W0141,W0142,W0232,W0311,W0312,W0603,W0511,W0613,E1101,E1103"

#  my take
COMMON_PYLINT=""
# line below get the msgid
COMMON_PYLINT='--msg-template="{msg_id}:{line:3d},{column}:{obj}:{msg} '
COMMON_PYLINT=${COMMON_PYLINT}" --variable-naming-style=any"

PYLINTOPTS=""                          # null start
PYLINTOPTS="C0103"                     # c0103 relax naming
#PYLINTOPTS=${PYLINTOPTS}"

# not the need for comma  --disable=pylintopts  x,y,z,a

PYLINTOPTS=${PYLINTOPTS}",C0325"       # c0325 allow parens in print 

echo "----------------------"
echo pylint ${COMMON_PYLINT} --disable=${PYLINTOPTS} $1 
echo "----------------------"
pylint ${COMMON_PYLINT} --disable=${PYLINTOPTS} $1 
