#!/bin/bash

# http://www.linuxjournal.com/content/using-named-pipes-fifos-bash


pipe=/tmp/testpipe
pipe=$HOME/.localpipe

# echo before
trap "rm -f $pipe" EXIT
# echo after

if [[ ! -p $pipe ]]; then
    mkfifo $pipe
fi

while true
do
    if read line <$pipe; then
        if [[ "$line" == 'quit' ]]; then
            break
        fi
        echo $line
    fi
done

echo "Reader exiting"
